# Generated by Django 5.0.6 on 2024-05-27 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0003_carrera_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_list', to='mallaCurricular.carrera')),
            ],
        ),
    ]
