# Generated by Django 5.0.6 on 2024-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0004_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='numero',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
