# Generated by Django 5.0.6 on 2024-05-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0006_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial'), ('DISTANCIA', 'Distancia')], default='PRESENCIAL', max_length=50),
        ),
    ]
