# Generated by Django 5.0.6 on 2024-05-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0007_carrera_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial'), ('DISTANCIA', 'Distancia')], default='PRESENCIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(help_text='Nombre de la facultad', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='siglas',
            field=models.CharField(blank=True, help_text='Siglas de la facultad', max_length=10),
        ),
    ]
