# Generated by Django 5.0.6 on 2024-05-28 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0008_alter_carrera_modalidad_alter_facultad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial'), ('DISTANCIA', 'Distancia')], default='PRESENCIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(help_text='Nombre de la facultad', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
