# Generated by Django 5.0.6 on 2024-05-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0009_alter_carrera_modalidad_alter_facultad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('SEMIPRESENCIAL', 'Semipresencial'), ('DISTANCIA', 'Distancia')], default='PRESENCIAL', max_length=50),
        ),
    ]
